### ISSUE TITLE
How can the Binder community highlight this repo?

### ISSUE THREAD

**Issue by choldgraf** [costrouc/nix-binder-example#1]
Hey there 👋 this is a really nice introduction to nix, and I'm wondering how the Binder community can highlight this so that people can use Binder as a way to learn nix.

It's a bit more complete in its treatment of nix than most of the examples in `github.com/binder-examples`...in that case, we often have a very short example there, and provide a link to the more complete example (that's what we do with JupyterLab).

Does that sound reasonable to you? Open to other ideas too!

**Comment by costrouc** [comment]
That sounds great with me. I have created a simpler repository that points to this one. 

https://github.com/costrouc/nix-binder-example-simple

Only the binder link will needs to be updated when I transfer the repository. Not sure exactly how you would like to do it.

**Comment by choldgraf** [comment]
Sounds good - I added a page to the Binder docs yesterday here: https://mybinder.readthedocs.io/en/latest/examples.html

We'll start collecting examples around specific use-cases, and I added your repo in there under "reproducibility". The hope is that this page will eventually be re-designed so that it has a nicer layout, but for now I just want to make sure that we don't lose track of the repository. Does that make sense?

**Comment by costrouc** [comment]
Yeah that does make sense. Looks great to me!

**Comment by choldgraf** [comment]
ok cool - I'll close this now. If you have thoughts on how the Binder community can show off stuff like this, I'd love to hear it. The main goal of the project is to empower people to more quickly interact with other open-source tools for things like reproducibility or communication!
